// utils/attendanceReportGenerator.js

import pdfMake from 'pdfmake/build/pdfmake';

let fontsLoaded = false;

const loadFonts = async () => {
    if (fontsLoaded) return;
    try {
        const pdfFontsModule = await import('pdfmake/build/vfs_fonts');
        if (pdfFontsModule.default && pdfFontsModule.default.pdfMake) {
            pdfMake.vfs = pdfFontsModule.default.pdfMake.vfs;
        } else if (pdfFontsModule.pdfMake) {
            pdfMake.vfs = pdfFontsModule.pdfMake.vfs;
        } else if (pdfFontsModule.default) {
            pdfMake.vfs = pdfFontsModule.default;
        } else {
            pdfMake.vfs = pdfFontsModule;
        }
        fontsLoaded = true;
    } catch (error) {
        console.warn('Could not load pdfmake fonts:', error);
    }
};

// Reusable header configuration - UPDATED
const getReportHeader = (schoolData, title, subtitle, pageOrientation = 'portrait') => {
    // Calculate line width based on page orientation
    const lineWidth = pageOrientation === 'landscape' ? 780 : 515;

    return {
        stack: [
            {
                columns: [
                    {
                        width: 80,
                        image: schoolData?.logo || 'data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAAAEAAAABCAYAAAAfFcSJAAAADUlEQVR42mNk+M9QDwADhgGAWjR9awAAAABJRU5ErkJggg==',
                        fit: [70, 70]
                    },
                    {
                        width: '*',
                        stack: [
                            {
                                text: schoolData?.schoolName || 'School Name',
                                style: 'schoolName',
                                alignment: 'center'
                            },
                            {
                                text: schoolData?.schoolAddress || 'School Address',
                                style: 'schoolAddress',
                                alignment: 'center'
                            },
                            {
                                text: [
                                    { text: 'Phone: ', bold: true },
                                    schoolData?.schoolPhone || 'N/A',
                                    { text: ' | Email: ', bold: true },
                                    schoolData?.schoolEmail || 'N/A'
                                ],
                                style: 'schoolContact',
                                alignment: 'center'
                            }
                        ]
                    },
                    {
                        width: 80,
                        text: ''
                    }
                ],
                margin: [30, 20, 30, 0]
            },
            {
                canvas: [
                    {
                        type: 'line',
                        x1: 0,
                        y1: 5,
                        x2: lineWidth, // Dynamic width based on orientation
                        y2: 5,
                        lineWidth: 2,
                        lineColor: '#667eea'
                    }
                ],
                margin: [30, 5, 30, 0]
            },
            {
                text: title,
                style: 'reportTitle',
                margin: [30, 10, 30, 5]
            },
            {
                text: subtitle,
                style: 'reportSubtitle',
                margin: [30, 0, 30, 15]
            }
        ]
    };
};



// Reusable footer configuration
const getReportFooter = (currentPage, pageCount, generatedBy) => {
    return {
        columns: [
            {
                text: `Generated by: ${generatedBy || 'System'}`,
                fontSize: 8,
                color: '#666666',
                alignment: 'left',
                margin: [40, 0, 0, 0]
            },
            {
                text: `Generated on: ${new Date().toLocaleString('en-IN', {
                    timeZone: 'Asia/Kolkata',
                    year: 'numeric',
                    month: 'short',
                    day: 'numeric',
                    hour: '2-digit',
                    minute: '2-digit'
                })}`,
                fontSize: 8,
                color: '#666666',
                alignment: 'center'
            },
            {
                text: `Page ${currentPage} of ${pageCount}`,
                fontSize: 8,
                color: '#666666',
                alignment: 'right',
                margin: [0, 0, 40, 0]
            }
        ],
        margin: [0, 10, 0, 10]
    };
};

// Format date helper
const formatDate = (dateString) => {
    const date = new Date(dateString);
    return date.toLocaleDateString('en-IN', {
        day: '2-digit',
        month: 'short',
        year: 'numeric'
    });
};

// Format date for column header (short format)
const formatDateShort = (dateString) => {
    const date = new Date(dateString);
    return date.toLocaleDateString('en-IN', {
        day: '2-digit'
    });
};

/**
 * Generate Attendance Report PDF
 */
export const generateAttendanceReport = async (reportData, schoolData, action = 'download') => {
    await loadFonts();

    const { type, className, sectionName, date, startDate, endDate, records, statistics } = reportData;

    let content = [];
    let title = '';
    let subtitle = '';
    let pageOrientation = 'portrait';

    if (type === 'single') {
        // Single Day Attendance Report
        title = 'DAILY ATTENDANCE REPORT';
        subtitle = `Class: ${className} - ${sectionName} | Date: ${formatDate(date)}`;

        // Statistics summary
        content.push({
            style: 'section',
            table: {
                widths: ['*', '*', '*', '*', '*'],
                body: [
                    [
                        { text: 'Total Students', style: 'tableHeader', alignment: 'center', fillColor: '#f5f5f5' },
                        { text: 'Present', style: 'tableHeader', alignment: 'center', fillColor: '#e8f5e9' },
                        { text: 'Absent', style: 'tableHeader', alignment: 'center', fillColor: '#ffebee' },
                        { text: 'Late', style: 'tableHeader', alignment: 'center', fillColor: '#fff3e0' },
                        { text: 'Attendance Rate', style: 'tableHeader', alignment: 'center', fillColor: '#e3f2fd' }
                    ],
                    [
                        { text: statistics.total_students, alignment: 'center', fontSize: 14, bold: true },
                        { text: statistics.present, alignment: 'center', fontSize: 14, bold: true, color: '#4caf50' },
                        { text: statistics.absent, alignment: 'center', fontSize: 14, bold: true, color: '#f44336' },
                        { text: statistics.late, alignment: 'center', fontSize: 14, bold: true, color: '#ff9800' },
                        { text: `${statistics.attendance_rate}%`, alignment: 'center', fontSize: 14, bold: true, color: '#2196f3' }
                    ]
                ]
            },
            layout: {
                hLineWidth: () => 1,
                vLineWidth: () => 1,
                hLineColor: () => '#667eea',
                vLineColor: () => '#e0e0e0'
            },
            margin: [0, 0, 0, 20]
        });

        // Student-wise attendance table
        const tableBody = [
            [
                { text: '#', style: 'tableHeader', fillColor: '#667eea', color: '#ffffff' },
                { text: 'Roll No', style: 'tableHeader', fillColor: '#667eea', color: '#ffffff' },
                { text: 'Student Name', style: 'tableHeader', fillColor: '#667eea', color: '#ffffff' },
                { text: 'Status', style: 'tableHeader', fillColor: '#667eea', color: '#ffffff' },
                { text: 'Remarks', style: 'tableHeader', fillColor: '#667eea', color: '#ffffff' }
            ]
        ];

        records.forEach((record, index) => {
            const statusColor =
                record.status === 'Present' ? '#4caf50' :
                    record.status === 'Absent' ? '#f44336' :
                        record.status === 'Late' ? '#ff9800' : '#2196f3';

            tableBody.push([
                { text: index + 1, alignment: 'center' },
                { text: record.student.roll_no, alignment: 'center' },
                { text: record.student.name },
                { text: record.status, alignment: 'center', color: statusColor, bold: true },
                { text: record.remarks || '-', fontSize: 9 }
            ]);
        });

        content.push({
            style: 'section',
            table: {
                widths: [40, 80, '*', 100, 150],
                body: tableBody
            },
            layout: {
                hLineWidth: (i) => i === 0 || i === 1 ? 1 : 0.5,
                vLineWidth: () => 0.5,
                hLineColor: (i) => i === 0 || i === 1 ? '#667eea' : '#e0e0e0',
                vLineColor: () => '#e0e0e0',
                fillColor: (i) => i === 0 ? '#667eea' : null
            }
        });

    } else {
        // Monthly Attendance Report - Day by Day Matrix
        pageOrientation = 'landscape';
        title = 'MONTHLY ATTENDANCE REPORT';
        subtitle = `Class: ${className} - ${sectionName} | Period: ${formatDate(startDate)} to ${formatDate(endDate)}`;

        const { students, dates, summary } = records;

        // Overall summary at top
        content.push({
            style: 'section',
            table: {
                widths: ['*', '*', '*', '*'],
                body: [
                    [
                        { text: 'Total Students', style: 'tableHeader', alignment: 'center', fillColor: '#f5f5f5' },
                        { text: 'Total Days', style: 'tableHeader', alignment: 'center', fillColor: '#f5f5f5' },
                        { text: 'Total Present', style: 'tableHeader', alignment: 'center', fillColor: '#e8f5e9' },
                        { text: 'Overall Rate', style: 'tableHeader', alignment: 'center', fillColor: '#e3f2fd' }
                    ],
                    [
                        { text: summary.total_students, alignment: 'center', fontSize: 12, bold: true },
                        { text: summary.total_days, alignment: 'center', fontSize: 12, bold: true },
                        { text: summary.total_present, alignment: 'center', fontSize: 12, bold: true, color: '#4caf50' },
                        { text: `${summary.overall_attendance_rate}%`, alignment: 'center', fontSize: 12, bold: true, color: '#2196f3' }
                    ]
                ]
            },
            layout: {
                hLineWidth: () => 1,
                vLineWidth: () => 1,
                hLineColor: () => '#667eea',
                vLineColor: () => '#e0e0e0'
            },
            margin: [0, 0, 0, 15]
        });

        // Legend
        content.push({
            columns: [
                // Date range at the start
                {
                    text: `(${formatDate(startDate)} - ${formatDate(endDate)})`,
                    fontSize: 9,
                    bold: true,
                    width: 150
                },
                // Spacer to push legend to the right
                { text: '', width: '*' },
                // Legend at the end
                { text: 'Legend:', fontSize: 9, bold: true, width: 50 },
                { text: 'P - Present', fontSize: 8, color: '#4caf50', width: 70 },
                { text: 'A - Absent', fontSize: 8, color: '#f44336', width: 70 },
                { text: 'L - Late', fontSize: 8, color: '#ff9800', width: 60 },
                { text: 'Lv - Leave', fontSize: 8, color: '#2196f3', width: 70 },
                { text: '- Not Marked', fontSize: 8, color: '#bdbdbd', width: 90 }
            ],
            margin: [0, 0, 0, 10]
        });


        // Build the attendance matrix table
        // Calculate dynamic column widths based on number of dates
        const numDates = dates.length;
        const dateColumnWidth = Math.max(18, Math.min(25, Math.floor(520 / (numDates + 8)))); // Dynamic width
        const fixedColumnsWidth = [10, 20, 70]; // S.No, Roll, Name
        const summaryColumnsWidth = [20, 20, 20, 20, 20]; // Total, P, A, L, %

        const columnWidths = [
            ...fixedColumnsWidth,
            ...Array(numDates).fill(dateColumnWidth),
            ...summaryColumnsWidth
        ];

        // Build header row
        const headerRow = [
            { text: '#', style: 'tableHeaderSmall', fillColor: '#667eea', color: '#ffffff', alignment: 'center' },
            { text: 'Roll', style: 'tableHeaderSmall', fillColor: '#667eea', color: '#ffffff', alignment: 'center' },
            { text: 'Student Name', style: 'tableHeaderSmall', fillColor: '#667eea', color: '#ffffff' }
        ];

        // Add date columns
        dates.forEach(date => {
            headerRow.push({
                text: formatDateShort(date),
                style: 'tableHeaderSmall',
                fillColor: '#667eea',
                color: '#ffffff',
                alignment: 'center',
                fontSize: 7
            });
        });

        // Add summary columns
        headerRow.push(
            { text: 'Total', style: 'tableHeaderSmall', fillColor: '#667eea', color: '#ffffff', alignment: 'center' },
            { text: 'P', style: 'tableHeaderSmall', fillColor: '#667eea', color: '#ffffff', alignment: 'center' },
            { text: 'A', style: 'tableHeaderSmall', fillColor: '#667eea', color: '#ffffff', alignment: 'center' },
            { text: 'L', style: 'tableHeaderSmall', fillColor: '#667eea', color: '#ffffff', alignment: 'center' },
            { text: '%', style: 'tableHeaderSmall', fillColor: '#667eea', color: '#ffffff', alignment: 'center' }
        );

        const tableBody = [headerRow];

        // Add student rows
        students.forEach((student, index) => {
            const row = [
                { text: index + 1, alignment: 'center', fontSize: 8 },
                { text: student.student.roll_no || '-', alignment: 'center', fontSize: 8 },
                { text: student.student.name, fontSize: 8 }
            ];

            // Add daily attendance
            student.daily_attendance.forEach(dayAtt => {
                const statusMap = {
                    'Present': { symbol: 'P', color: 'blue', bg: '#e8f5e9' },
                    'Absent': { symbol: 'A', color: 'red', bg: '#ffebee' },
                    'Late': { symbol: 'L', color: '#ff9800', bg: '#fff3e0' },
                    'Leave': { symbol: 'Lv', color: '#2196f3', bg: '#e3f2fd' },
                    'Medical_Leave': { symbol: 'ML', color: '#2196f3', bg: '#e3f2fd' },
                    'Excused': { symbol: 'E', color: '#9e9e9e', bg: '#f5f5f5' },
                    'Not Marked': { symbol: '-', color: '#bdbdbd', bg: null }
                };

                const statusInfo = statusMap[dayAtt.status] || { symbol: '-', color: '#bdbdbd', bg: null };

                row.push({
                    text: statusInfo.symbol,
                    alignment: 'center',
                    fontSize: 7,
                    bold: true,
                    color: statusInfo.color,
                    fillColor: statusInfo.bg
                });
            });

            // Add summary columns
            const percentageColor =
                student.summary.attendance_percentage >= 90 ? '#4caf50' :
                    student.summary.attendance_percentage >= 75 ? '#ff9800' : '#f44336';

            row.push(
                { text: student.summary.total_days, alignment: 'center', fontSize: 8 },
                { text: student.summary.present_count, alignment: 'center', fontSize: 8, color: '#4caf50' },
                { text: student.summary.absent_count, alignment: 'center', fontSize: 8, color: '#f44336' },
                { text: student.summary.late_count, alignment: 'center', fontSize: 8, color: '#ff9800' },
                { text: `${student.summary.attendance_percentage}%`, alignment: 'center', fontSize: 7, bold: true, color: percentageColor }
            );

            tableBody.push(row);
        });

        content.push({
            style: 'section',
            table: {
                widths: columnWidths,
                body: tableBody,
                headerRows: 1
            },
            layout: {
                hLineWidth: (i, node) => (i === 0 || i === 1 || i === node.table.body.length) ? 1 : 0.3,
                vLineWidth: () => 0.3,
                hLineColor: (i) => (i === 0 || i === 1) ? '#667eea' : '#e0e0e0',
                vLineColor: () => '#e0e0e0'
            }
        });

        // Add attendance criteria
        content.push({
            text: 'Attendance Criteria: ≥90% - Excellent | 75-89% - Good | 60-74% - Warning | <60% - Critical',
            fontSize: 8,
            italics: true,
            color: '#666666',
            margin: [0, 10, 0, 0]
        });
    }

    // Signature section
    content.push({
        columns: [
            {
                width: '*',
                stack: [
                    { text: '\n\n\n', fontSize: 8 },
                    { canvas: [{ type: 'line', x1: 0, y1: 0, x2: 120, y2: 0, lineWidth: 1 }] },
                    { text: 'Class Teacher Signature', fontSize: 9, margin: [0, 5, 0, 0] }
                ]
            },
            {
                width: '*',
                text: ''
            },
            {
                width: '*',
                stack: [
                    { text: '\n\n\n', fontSize: 8 },
                    { canvas: [{ type: 'line', x1: 0, y1: 0, x2: 120, y2: 0, lineWidth: 1 }] },
                    { text: 'Principal Signature', fontSize: 9, margin: [0, 5, 0, 0], alignment: 'right' }
                ],
                alignment: 'right'
            }
        ],
        margin: [0, 30, 0, 0]
    });

    const docDefinition = {
        pageSize: 'A4',
        pageOrientation: pageOrientation,
        pageMargins: pageOrientation === 'landscape' ? [30, 140, 30, 50] : [40, 140, 40, 60],
        header: (currentPage, pageCount) => {
            if (currentPage === 1) {
                return getReportHeader(schoolData, title, subtitle, pageOrientation); // Pass orientation
            }
            return {
                stack: [
                    {
                        text: title,
                        alignment: 'center',
                        fontSize: 11,
                        bold: true,
                        color: '#667eea',
                        margin: [0, 15, 0, 2]
                    },
                    {
                        text: subtitle,
                        alignment: 'center',
                        fontSize: 9,
                        color: '#666666',
                        margin: [0, 0, 0, 10]
                    }
                ]
            };
        },
        footer: (currentPage, pageCount) => {
            return getReportFooter(currentPage, pageCount, schoolData?.generatedBy);
        },
        content: content,
        styles: {
            schoolName: {
                fontSize: 18,
                bold: true,
                color: '#667eea',
                margin: [0, 5, 0, 2]
            },
            schoolAddress: {
                fontSize: 10,
                color: '#666666',
                margin: [0, 2, 0, 2]
            },
            schoolContact: {
                fontSize: 9,
                color: '#666666',
                margin: [0, 2, 0, 5]
            },
            reportTitle: {
                fontSize: 16,
                bold: true,
                alignment: 'center',
                color: '#667eea'
            },
            reportSubtitle: {
                fontSize: 10, // Reduced from 11 to fit better
                alignment: 'center',
                color: '#666666',
                lineHeight: 1.2 // Added line height for better spacing
            },
            tableHeader: {
                fontSize: 10,
                bold: true,
                alignment: 'left'
            },
            tableHeaderSmall: {
                fontSize: 8,
                bold: true,
                alignment: 'left'
            },
            section: {
                margin: [0, 5, 0, 5]
            }
        },
        defaultStyle: {
            fontSize: 10,
            color: '#333333'
        }
    };


    if (action === 'print') {
        pdfMake.createPdf(docDefinition).print();
    } else if (action === 'download') {
        const filename = type === 'single'
            ? `Attendance_${className}_${sectionName}_${date}.pdf`
            : `Attendance_Register_${className}_${sectionName}_${startDate}_to_${endDate}.pdf`;
        pdfMake.createPdf(docDefinition).download(filename);
    } else {
        pdfMake.createPdf(docDefinition).open();
    }
};
