export const getReportHeader = (schoolData, title, subtitle, pageOrientation = 'portrait') => {
    const lineWidth = pageOrientation === 'landscape' ? 780 : 515;

    return {
        stack: [
            {
                columns: [
                    {
                        width: 80,
                        image: schoolData?.logo || 'data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAAAEAAAABCAYAAAAfFcSJAAAADUlEQVR42mNk+M9QDwADhgGAWjR9awAAAABJRU5ErkJggg==',
                        fit: [70, 70]
                    },
                    {
                        width: '*',
                        stack: [
                            {
                                text: schoolData?.schoolName || 'School Name',
                                style: 'schoolName',
                                alignment: 'center'
                            },
                            {
                                text: schoolData?.schoolAddress || 'School Address',
                                style: 'schoolAddress',
                                alignment: 'center'
                            },
                            {
                                text: [
                                    { text: 'Phone: ', bold: true },
                                    schoolData?.schoolPhone || 'N/A',
                                    { text: ' | Email: ', bold: true },
                                    schoolData?.schoolEmail || 'N/A'
                                ],
                                style: 'schoolContact',
                                alignment: 'center'
                            }
                        ]
                    },
                    {
                        width: 80,
                        text: ''
                    }
                ],
                margin: [30, 20, 30, 0]
            },
            {
                canvas: [
                    {
                        type: 'line',
                        x1: 0,
                        y1: 5,
                        x2: lineWidth,
                        y2: 5,
                        lineWidth: 2,
                        lineColor: '#667eea'
                    }
                ],
                margin: [30, 5, 30, 0]
            },
            {
                text: title,
                style: 'reportTitle',
                margin: [30, 10, 30, 5]
            },
            {
                text: subtitle,
                style: 'reportSubtitle',
                margin: [30, 0, 30, 15]
            }
        ]
    };
};

export const getReportFooter = (currentPage, pageCount, generatedBy) => {
    return {
        columns: [
            {
                text: `Generated by: ${generatedBy || 'System'}`,
                fontSize: 8,
                color: '#666666',
                alignment: 'left',
                margin: [40, 0, 0, 0]
            },
            {
                text: `Generated on: ${new Date().toLocaleString('en-IN', {
                    timeZone: 'Asia/Kolkata',
                    year: 'numeric',
                    month: 'short',
                    day: 'numeric',
                    hour: '2-digit',
                    minute: '2-digit'
                })}`,
                fontSize: 8,
                color: '#666666',
                alignment: 'center'
            },
            {
                text: `Page ${currentPage} of ${pageCount}`,
                fontSize: 8,
                color: '#666666',
                alignment: 'right',
                margin: [0, 0, 40, 0]
            }
        ],
        margin: [0, 10, 0, 10]
    };
};


export const getSignatureSection = (signatures = []) => {
    const defaultSignatures = [
        { label: 'Class Teacher Signature', position: 'left' },
        { label: 'Principal Signature', position: 'right' }
    ];

    const sigs = signatures.length > 0 ? signatures : defaultSignatures;
    const columns = [];

    sigs.forEach(sig => {
        const alignment = sig.position === 'left' ? 'left' : sig.position === 'right' ? 'right' : 'center';

        columns.push({
            width: '*',
            stack: [
                { text: '\n\n\n', fontSize: 8 },
                { canvas: [{ type: 'line', x1: 0, y1: 0, x2: 120, y2: 0, lineWidth: 1 }], alignment },
                { text: sig.label, fontSize: 9, margin: [0, 5, 0, 0], alignment }
            ]
        });

        // Add spacer between signatures
        if (sigs.indexOf(sig) < sigs.length - 1) {
            columns.push({ width: '*', text: '' });
        }
    });

    return {
        columns,
        margin: [0, 30, 0, 0]
    };
};

/**
 * Common PDF Styles - Reusable across all reports
 */
export const commonPdfStyles = {
    schoolName: {
        fontSize: 18,
        bold: true,
        color: '#667eea',
        margin: [0, 5, 0, 2]
    },
    schoolAddress: {
        fontSize: 10,
        color: '#666666',
        margin: [0, 2, 0, 2]
    },
    schoolContact: {
        fontSize: 9,
        color: '#666666',
        margin: [0, 2, 0, 5]
    },
    reportTitle: {
        fontSize: 16,
        bold: true,
        alignment: 'center',
        color: '#667eea'
    },
    reportSubtitle: {
        fontSize: 10,
        alignment: 'center',
        color: '#666666',
        lineHeight: 1.2
    },
    tableHeader: {
        fontSize: 10,
        bold: true,
        alignment: 'left',
        color: '#ffffff',
        fillColor: '#667eea'
    },
    tableHeaderSmall: {
        fontSize: 8,
        bold: true,
        alignment: 'left'
    },
    sectionTitle: {
        fontSize: 12,
        bold: true,
        color: '#667eea',
        margin: [0, 10, 0, 5]
    },
    section: {
        margin: [0, 5, 0, 5]
    }
};

/**
 * Format date helper
 */
export const formatDate = (dateString) => {
    const date = new Date(dateString);
    return date.toLocaleDateString('en-IN', {
        day: '2-digit',
        month: 'short',
        year: 'numeric'
    });
};

/**
 * Load pdfmake fonts - Call once at app startup
 */
let fontsLoaded = false;

export const loadPdfFonts = async () => {
    if (fontsLoaded) return;
    try {
        const pdfFontsModule = await import('pdfmake/build/vfs_fonts');
        const pdfMake = (await import('pdfmake/build/pdfmake')).default;

        if (pdfFontsModule.default && pdfFontsModule.default.pdfMake) {
            pdfMake.vfs = pdfFontsModule.default.pdfMake.vfs;
        } else if (pdfFontsModule.pdfMake) {
            pdfMake.vfs = pdfFontsModule.pdfMake.vfs;
        } else if (pdfFontsModule.default) {
            pdfMake.vfs = pdfFontsModule.default;
        } else {
            pdfMake.vfs = pdfFontsModule;
        }
        fontsLoaded = true;
    } catch (error) {
        console.warn('Could not load pdfmake fonts:', error);
    }
};
